/**
 * Stage 15.1 Part C — No-Show Re-Engagement Sequence.
 *
 * 5-touch AI-generated re-engagement sequence triggered after a first no-show.
 * Each touch is generated by the reasoning engine with full context.
 * Cancels automatically when a reply is received.
 *
 * Touch schedule:
 * 1. Immediate (5-10 min after detection)
 * 2. +3 hours
 * 3. +24 hours
 * 4. +72 hours (3 days)
 * 5. +168 hours (7 days)
 *
 * Stage progression (deterministic):
 * - Reply + reschedule → stay in demo_booked, reset no_show_count
 * - After Touch 2 + 48h no response → pending_clarification
 * - All 5 exhausted → stalled
 * - Lead explicitly declines → closed_lost
 */

import { inngest } from "@/lib/inngest/client";
import { createAdminSupabaseClient } from "@/lib/supabase-admin";
import { draftOutreachEmail } from "@/lib/email/email-sender";
import { dispatchNotification } from "@/lib/skyler/notifications";
import { validateAndLog } from "@/lib/skyler/pipeline/state-machine";
import Anthropic from "@anthropic-ai/sdk";

// Touch delays in milliseconds
const TOUCH_DELAYS = [
  5 * 60 * 1000,           // Touch 1: 5 min
  3 * 60 * 60 * 1000,      // Touch 2: 3 hours
  24 * 60 * 60 * 1000,     // Touch 3: 24 hours
  72 * 60 * 60 * 1000,     // Touch 4: 72 hours (3 days)
  168 * 60 * 60 * 1000,    // Touch 5: 168 hours (7 days)
];

const TONE_GUIDANCE = [
  'Quick, empathetic. "Something came up? Here\'s how to reconnect."',
  "Slightly more formal. Restate value. Include rebooking option.",
  "New angle. Share a relevant case study or resource if available.",
  "Alternative format. Offer async demo or recorded walkthrough.",
  '"Closing the loop" — direct, brief. Last attempt before moving on.',
];

export const noShowReengagement = inngest.createFunction(
  {
    id: "no-show-reengagement",
    retries: 1,
    cancelOn: [
      {
        event: "skyler/pipeline.reply.received",
        if: "async.data.pipelineId == event.data.pipelineId",
      },
    ],
  },
  { event: "skyler/no-show.re-engage" },
  async ({ event, step }) => {
    const { workspaceId, calendarEventId, pipelineId } = event.data as {
      workspaceId: string;
      calendarEventId: string;
      pipelineId: string;
    };

    // Mark re-engagement as active
    await step.run("activate-reengagement", async () => {
      const db = createAdminSupabaseClient();
      await db
        .from("skyler_sales_pipeline")
        .update({
          re_engagement_status: "active",
          re_engagement_touch: 0,
          re_engagement_started_at: new Date().toISOString(),
          cadence_paused: true,
          updated_at: new Date().toISOString(),
        })
        .eq("id", pipelineId);
    });

    // Load lead + workspace context once
    const context = await step.run("load-context", async () => {
      const db = createAdminSupabaseClient();

      const [pipelineResult, calEventResult, workspaceResult, integrationsResult] = await Promise.all([
        db.from("skyler_sales_pipeline")
          .select("contact_name, contact_email, company_name, stage, conversation_thread, no_show_count")
          .eq("id", pipelineId)
          .single(),
        db.from("calendar_events")
          .select("title, start_time, end_time")
          .eq("id", calendarEventId)
          .single(),
        db.from("workspaces")
          .select("name, settings")
          .eq("id", workspaceId)
          .single(),
        db.from("integrations")
          .select("provider")
          .eq("workspace_id", workspaceId)
          .eq("status", "connected"),
      ]);

      const pipeline = pipelineResult.data;
      const calEvent = calEventResult.data;
      const workspace = workspaceResult.data;
      const integrations = (integrationsResult.data ?? []).map((i) => i.provider as string);

      if (!pipeline) throw new Error(`Pipeline ${pipelineId} not found`);

      // Determine rebooking capability
      const hasCalendly = integrations.includes("calendly");
      const hasCalendar = integrations.includes("google-calendar") || integrations.includes("outlook");
      let rebookingCapability = "Ask the lead to suggest times. Flag the user to book manually.";
      if (hasCalendly) {
        rebookingCapability = "Include a Calendly booking link for the lead to pick a time.";
      } else if (hasCalendar) {
        rebookingCapability = "Check the user's availability and suggest 2-3 specific time slots.";
      }

      // Get owner name
      const { data: memberData } = await db
        .from("workspace_memberships")
        .select("profiles(full_name)")
        .eq("workspace_id", workspaceId)
        .eq("role", "owner")
        .limit(1)
        .single();

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const profile = (memberData as any)?.profiles;
      const ownerName: string = Array.isArray(profile)
        ? profile[0]?.full_name ?? "Sales Team"
        : profile?.full_name ?? "Sales Team";

      // Email history summary
      const thread = (pipeline.conversation_thread ?? []) as Array<{ role: string; content: string; subject?: string; timestamp: string }>;
      const recentEmails = thread.slice(-5).map((e) => `[${e.role}] ${e.subject ?? "(no subject)"}: ${e.content.slice(0, 100)}...`).join("\n");

      return {
        contactName: pipeline.contact_name as string,
        contactEmail: pipeline.contact_email as string,
        companyName: (pipeline.company_name as string) ?? "their company",
        stage: pipeline.stage as string,
        noShowCount: (pipeline.no_show_count as number) ?? 1,
        meetingTitle: (calEvent?.title as string) ?? "Demo",
        meetingTime: calEvent?.start_time ? new Date(calEvent.start_time as string).toLocaleString("en-GB", { weekday: "long", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }) : "the scheduled time",
        connectedIntegrations: integrations.join(", ") || "none",
        rebookingCapability,
        ownerName,
        companyDisplayName: (workspace?.name as string) ?? "our team",
        recentEmails: recentEmails || "(no prior emails)",
      };
    });

    // Execute 5 touches with waits between them
    for (let touch = 0; touch < 5; touch++) {
      const touchNum = touch + 1;

      // Sleep before this touch (Touch 1 delay is just 5 min)
      if (touch > 0) {
        const delaySecs = Math.ceil(TOUCH_DELAYS[touch] / 1000);
        await step.sleep(`wait-before-touch-${touchNum}`, `${delaySecs}s`);
      } else {
        // Touch 1: brief delay
        await step.sleep("wait-before-touch-1", "300s");
      }

      // Generate and send this touch
      const touchResult = await step.run(`send-touch-${touchNum}`, async () => {
        const db = createAdminSupabaseClient();

        // Generate email via AI
        const prompt = buildReengagementPrompt(context, touchNum);
        const email = await generateReengagementEmail(prompt);

        if (!email) {
          console.error(`[no-show-reengagement] Failed to generate touch ${touchNum} for ${context.contactName}`);
          return { sent: false };
        }

        // Store as pending action (goes through approval queue)
        const { actionId } = await draftOutreachEmail(db, {
          workspaceId,
          pipelineId,
          to: context.contactEmail,
          subject: email.subject,
          htmlBody: email.body.replace(/\n/g, "<br>"),
          textBody: email.body,
        });

        // Update re-engagement tracking
        const nextTouchAt = touch < 4
          ? new Date(Date.now() + TOUCH_DELAYS[touch + 1]).toISOString()
          : null;

        await db
          .from("skyler_sales_pipeline")
          .update({
            re_engagement_touch: touchNum,
            last_re_engagement_action: {
              type: "email_drafted",
              timestamp: new Date().toISOString(),
              summary: `Touch ${touchNum}: "${email.subject}"`,
              action_id: actionId,
            },
            next_re_engagement_at: nextTouchAt,
            updated_at: new Date().toISOString(),
          })
          .eq("id", pipelineId);

        // Log to pipeline_events
        try {
          await db.from("pipeline_events").insert({
            lead_id: pipelineId,
            event_type: "reengagement_touch",
            source: "no_show_reengagement",
            source_detail: `touch_${touchNum}_of_5`,
            payload: {
              touch: touchNum,
              subject: email.subject,
              action_id: actionId,
              reasoning: email.reasoning,
            },
          });
        } catch { /* audit logging should not block */ }

        console.log(`[no-show-reengagement] Touch ${touchNum}/5 drafted for ${context.contactName}: "${email.subject}"`);
        return { sent: true, actionId, subject: email.subject };
      });

      if (!touchResult.sent) continue;

      // After Touch 2, if no response in 48h → move to pending_clarification
      if (touchNum === 2) {
        const reply = await step.waitForEvent(`wait-reply-after-touch-2`, {
          event: "skyler/pipeline.reply.received",
          timeout: "48h",
          if: `async.data.pipelineId == '${pipelineId}'`,
        });

        if (reply) {
          // Reply received — handled by cancelOn or we exit here
          await step.run("handle-reply-touch-2", async () => {
            const db = createAdminSupabaseClient();
            await db
              .from("skyler_sales_pipeline")
              .update({
                re_engagement_status: "completed",
                updated_at: new Date().toISOString(),
              })
              .eq("id", pipelineId);
          });
          return { status: "reply_received", touch: touchNum, pipelineId };
        }

        // No response after 48h — move to pending_clarification
        await step.run("move-to-pending-clarification", async () => {
          const db = createAdminSupabaseClient();
          const { data: current } = await db
            .from("skyler_sales_pipeline")
            .select("stage")
            .eq("id", pipelineId)
            .single();

          if (current?.stage && !["pending_clarification", "closed_won", "closed_lost", "stalled"].includes(current.stage)) {
            await validateAndLog(
              pipelineId,
              current.stage,
              "pending_clarification",
              "no_show_reengagement",
              "48h_no_response_after_touch_2",
            );

            await db
              .from("skyler_sales_pipeline")
              .update({
                stage: "pending_clarification",
                updated_at: new Date().toISOString(),
              })
              .eq("id", pipelineId);

            console.log(`[no-show-reengagement] ${pipelineId} → pending_clarification (48h no response)`);
          }
        });

        // Continue with remaining touches
        continue;
      }

      // For other touches, wait for reply until next touch delay
      if (touchNum < 5 && touchNum !== 2) {
        const waitSecs = Math.ceil(TOUCH_DELAYS[touch + 1] / 1000);
        const reply = await step.waitForEvent(`wait-reply-after-touch-${touchNum}`, {
          event: "skyler/pipeline.reply.received",
          timeout: `${waitSecs}s`,
          if: `async.data.pipelineId == '${pipelineId}'`,
        });

        if (reply) {
          await step.run(`handle-reply-touch-${touchNum}`, async () => {
            const db = createAdminSupabaseClient();
            await db
              .from("skyler_sales_pipeline")
              .update({
                re_engagement_status: "completed",
                updated_at: new Date().toISOString(),
              })
              .eq("id", pipelineId);
          });
          return { status: "reply_received", touch: touchNum, pipelineId };
        }
      }
    }

    // All 5 touches exhausted — move to stalled
    await step.run("exhaust-reengagement", async () => {
      const db = createAdminSupabaseClient();

      const { data: current } = await db
        .from("skyler_sales_pipeline")
        .select("stage")
        .eq("id", pipelineId)
        .single();

      if (current?.stage && !["closed_won", "closed_lost", "stalled"].includes(current.stage)) {
        await validateAndLog(
          pipelineId,
          current.stage,
          "stalled",
          "no_show_reengagement",
          "all_5_touches_exhausted",
        );

        await db
          .from("skyler_sales_pipeline")
          .update({
            stage: "stalled",
            re_engagement_status: "completed",
            next_re_engagement_at: null,
            updated_at: new Date().toISOString(),
          })
          .eq("id", pipelineId);
      }

      // Notify
      await dispatchNotification(db, {
        workspaceId,
        eventType: "reengagement_exhausted",
        pipelineId,
        title: `Re-engagement exhausted: ${context.contactName}`,
        body: `${context.contactName} hasn't responded after 5 re-engagement attempts. Moved to stalled.`,
        metadata: { touches: 5 },
      });

      console.log(`[no-show-reengagement] ${pipelineId} → stalled (all 5 touches exhausted)`);
    });

    return { status: "exhausted", pipelineId, touches: 5 };
  }
);

// ── AI email generation ────────────────────────────────────────────────────

function buildReengagementPrompt(
  ctx: {
    contactName: string;
    companyName: string;
    meetingTitle: string;
    meetingTime: string;
    noShowCount: number;
    connectedIntegrations: string;
    rebookingCapability: string;
    ownerName: string;
    companyDisplayName: string;
    recentEmails: string;
  },
  touchNum: number,
): string {
  return `You are Skyler, an AI sales assistant writing a re-engagement email after a no-show.

<no_show_context>
Lead: ${ctx.contactName}, ${ctx.companyName}
Meeting that was missed: ${ctx.meetingTitle}, scheduled ${ctx.meetingTime}
No-show count: ${ctx.noShowCount} (${ctx.noShowCount === 1 ? "first no-show" : "repeat"})
Previous engagement:
${ctx.recentEmails}

Connected integrations: ${ctx.connectedIntegrations || "none"}

Rebooking capability:
${ctx.rebookingCapability}

Touch number: ${touchNum} of 5
Tone guidance:
- ${TONE_GUIDANCE[touchNum - 1]}

Keep emails under 125 words. Subject lines under 7 words.
Never blame the lead for missing the meeting.
Each touch must add new value, not repeat the same ask.
Sign off as ${ctx.ownerName} from ${ctx.companyDisplayName}.
</no_show_context>

Respond with ONLY valid JSON:
{
  "subject": "...",
  "body": "...",
  "reasoning": "Why this approach for touch ${touchNum}"
}`;
}

async function generateReengagementEmail(
  prompt: string,
): Promise<{ subject: string; body: string; reasoning: string } | null> {
  try {
    const client = new Anthropic();
    const response = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 500,
      messages: [{ role: "user", content: prompt }],
    });

    const text = response.content
      .filter((b) => b.type === "text")
      .map((b) => b.text)
      .join("");

    // Extract JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return null;

    const parsed = JSON.parse(jsonMatch[0]);
    return {
      subject: parsed.subject ?? "Following up",
      body: parsed.body ?? "",
      reasoning: parsed.reasoning ?? "",
    };
  } catch (err) {
    console.error("[no-show-reengagement] AI generation failed:", err instanceof Error ? err.message : err);
    return null;
  }
}
